// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-dUsc6OpgYjMn6pXAvR31Xk2jUbcj14E',
    appId: '1:1000495641242:web:add6cdf90be74f2f4c6523',
    messagingSenderId: '1000495641242',
    projectId: 'instagram-clone-be69c',
    authDomain: 'instagram-clone-be69c.firebaseapp.com',
    storageBucket: 'instagram-clone-be69c.appspot.com',
    measurementId: 'G-N5K920VQJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0y1QIf3oaJzzM0k6-F7n0CHK5P3TbJ_s',
    appId: '1:1000495641242:android:07923931ee24821d4c6523',
    messagingSenderId: '1000495641242',
    projectId: 'instagram-clone-be69c',
    storageBucket: 'instagram-clone-be69c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ2lkY4alNmDtozn02XU-3XC9jwZU40kk',
    appId: '1:1000495641242:ios:14d85c9fed4021524c6523',
    messagingSenderId: '1000495641242',
    projectId: 'instagram-clone-be69c',
    storageBucket: 'instagram-clone-be69c.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ2lkY4alNmDtozn02XU-3XC9jwZU40kk',
    appId: '1:1000495641242:ios:587f674abbe960eb4c6523',
    messagingSenderId: '1000495641242',
    projectId: 'instagram-clone-be69c',
    storageBucket: 'instagram-clone-be69c.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
